// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2s_3RbCvT9rgKYKjvJKBiHUPNr_JbeT4',
    appId: '1:126243505392:web:100df642ecc9069f7d6e35',
    messagingSenderId: '126243505392',
    projectId: 'bicharsetu-699d4',
    authDomain: 'bicharsetu-699d4.firebaseapp.com',
    storageBucket: 'bicharsetu-699d4.firebasestorage.app',
    measurementId: 'G-ZMGB3FFFNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfA4BriDALHOXv9Sxx2sEfDAHsGSAqPPI',
    appId: '1:126243505392:android:beac52259b7dbcb17d6e35',
    messagingSenderId: '126243505392',
    projectId: 'bicharsetu-699d4',
    storageBucket: 'bicharsetu-699d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrdg4_Iru8_60n_EBxCJ-8_Mpge6kkOc',
    appId: '1:126243505392:ios:888f993615fe83087d6e35',
    messagingSenderId: '126243505392',
    projectId: 'bicharsetu-699d4',
    storageBucket: 'bicharsetu-699d4.firebasestorage.app',
    iosBundleId: 'com.example.bicharSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrdg4_Iru8_60n_EBxCJ-8_Mpge6kkOc',
    appId: '1:126243505392:ios:888f993615fe83087d6e35',
    messagingSenderId: '126243505392',
    projectId: 'bicharsetu-699d4',
    storageBucket: 'bicharsetu-699d4.firebasestorage.app',
    iosBundleId: 'com.example.bicharSetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2s_3RbCvT9rgKYKjvJKBiHUPNr_JbeT4',
    appId: '1:126243505392:web:f239c0cf850a0f1c7d6e35',
    messagingSenderId: '126243505392',
    projectId: 'bicharsetu-699d4',
    authDomain: 'bicharsetu-699d4.firebaseapp.com',
    storageBucket: 'bicharsetu-699d4.firebasestorage.app',
    measurementId: 'G-L3ZGP87C0Y',
  );
}
